### PR TITLE
Add initial support for MD automation

### PR DESCRIPTION
**Pull request by Jalle19**
On units with the old-style EDA control panel the mode doesn't seem to be reflected on the control panel, but the Modbus register sticks and the update seems to go through. Would have to monitor the device to see whether target temperature is adjusted accordingly when eco mode is on.

@kailampi can you try this branch?

### CODE REVIEW

**Comment by kailampi** [comment]
Seems to do the trick!

eco

**Comment by Jalle19** [comment]
Great! I'll rename "eco mode" to just "eco" since the other modes don't contain "mode" in the name either.

**Comment by Jalle19** [comment]
@kailampi can you try the latest changes here? The device model name should be "Pingvin eco EDE/MDE" now, and the switch in Home Assistant should be named just "Eco".

**Comment by Jalle19** [comment]
Thanks!

**Pull request merged**
