### PR TITLE
Improve device identifier

### PR DESCRIPTION
**Pull request by Jalle19**
* fan type, heating and cooling elements exposed
* MQTT device identifier revamped to not rely on serial number

Screenshot-20220110164439-331x293

@tomrosenback what do you think? If you try this out you'll have to remove the existing MQTT device first because the `node_id` used for discovery has changed (hopefully for the last time).

### CODE REVIEW

**Comment by Jalle19** [comment]
I left the firmware version there since there's a dedicated field for it in Home Assistant's device information structure :shrug:

**Comment by tomrosenback** [comment]
Device identifier looks good now! However I noticed that all entities are lacking a enervent / eda prefix which would make them easier to find when searching for them. The prefix needs to be in the config topic when publishing, eg

image

homeassistant/switch/enervent-Pandion-EC/overPressure/config would need to be homeassistant/switch/enervent-Pandion-EC/eda_overPressure/config

to get switch.eda_overpressure, and also HA handles the topics only in lowercase so maybe also publish the config atleast with lowercase?

**Comment by Jalle19** [comment]
> maybe also publish the config atleast with lowercase?

Yeah I thought about that as well, lowercase would look better and feel more natural in MQTT topic context.

> all entities are lacking a enervent / eda prefix which would make them easier to find when searching for them

You're right, it would be good to add a prefix while we still can (after anyone uses this it's annoying to change).

**Comment by Jalle19** [comment]
@tomrosenback added an entity name prefix and changed the device identifier to be lower-case. Some code duplication fixed as well

Screenshot-20220110184507-602x527
.

**Review by tomrosenback — APPROVED** [review]
LGTM! Tested also, all ok now.

**Comment by tomrosenback** [comment]
Is there something still open here? If not, please merge.

**Comment by Jalle19** [comment]
Not really, merging. Thanks for the review!

**Pull request merged**
