### PR TITLE
Make the addon more HA friendly

### PR DESCRIPTION
**Pull request by tomrosenback**
Adding the necessary repo details / structure to make the addon easier to install directly in HA. Also adds more configuration options to the HA side, used as parameters for the application.

Added more parameters to the eda-modbus-bridge.mjs call which is not yet consumed by this script.

### CODE REVIEW

**Comment by tomrosenback** [comment]
You can test this by adding the repo of my fork to your HA instance following the instructions in the readme in the addon folder.

**Comment by Jalle19** [comment]
Thanks for the pull request! Is it possible to have the addon repository in a separate git repository so we don't have to move all the files in this one?

**Comment by tomrosenback** [comment]
Would be possible with another repo and having repo as a submodule in there.

**Comment by Jalle19** [comment]
I think I'd prefer that. Can you undo the moving of the files so we can get the settings/config changes in?

**Comment by Jalle19** [comment]
Hmm, I just had a look at https://github.com/hassio-addons/addon-example and it seems like the structure you proposed is the suggested one, regardless of whether the repository is defined in this git repository or in another. So go ahead with your move!

**Comment by tomrosenback** [comment]
Should not make any big difference for end users how the repo is structured, those that have already installed might need to change some of their paths but otherwise it should be just fine with only this repo.

Fixed some merge conflicts, feel free to merge after testing :D

**Comment by tomrosenback** [comment]
Merge conflict fixes.

**Comment by Jalle19** [comment]
Looks good, I'll hold of on merging my own changes until this is in so you don't have to keep rebasing.

**Comment by tomrosenback** [comment]
Just got all up til my latest rebase tested with HA, all works as. One flaw but I will add that as a separate issue regarding unit type.

I don´t have write access to this repo so you will need to do the merge when you feel it is time for it. If you have other changes pending still, just push them in, rebasing has not been an issue yet.

**Comment by Jalle19** [comment]
Thanks, I'll try getting this merged tomorrow. Working on MQTT discovery here so I don't have to rely on custom configured Restful switches.

**Comment by tomrosenback** [comment]
Sounds good. Discovery is amazing, let me know if I can help somehow.

**Comment by Jalle19** [comment]
Looking over other people's addon repositories it seems like the most common pattern is indeed to use a separate git repository as the "addon repository", and then in the addon directory all the Home Assistant addon related files (Dockerfile, logo.png, icon.png etc.) are stored.

I'll set up a new repository for this, I would like to keep this software usable without Home Assistant as well (that's how it started out, basically just a HTTP API run by systemd).

**Comment by Jalle19** [comment]
https://github.com/Jalle19/home-assistant-addon-repository

**Comment by tomrosenback** [comment]
While I do agree on your last 2 comments, PR #12 mainly focuses on HA it is a half and half what is "best". But this is up to you to decide, let me know if you want me to move any part of this PR into the other repo.

**Comment by Jalle19** [comment]
I've made what I think is a working skeleton here: https://github.com/Jalle19/home-assistant-addon-repository. I'll give you write access to the repository so you can experiment more easily. Would be great if you could "port" the changes from this pull request to there?

I amended one of the commits to be in your name.

**Comment by tomrosenback** [comment]
I can do that.

**Comment by tomrosenback** [comment]
Ported to https://github.com/Jalle19/home-assistant-addon-repository, not including this in this repo.

**Pull request closed without merging**
