### PR TITLE
Divide version value by 100 to get correct version

### PR DESCRIPTION
**Pull request by tomrosenback**
Version number reported by summary is off by a multiplier of 100, lets divide it and get correct value out.

### CODE REVIEW

**Comment by Jalle19** [comment]
Indeed, thanks! I noticed but never got around to fixing it.

**Comment by Jalle19** [comment]
Would be nice to find the appropriate registers for e.g. the "eco ede" part (my control panel shows it under Information). If you find anything let me know.

**Comment by tomrosenback** [comment]
Have not managed to find anything else than the registry file that you have also. So not much luck on that.

**Comment by Jalle19** [comment]
I found them! See #14

**Pull request merged**
